-- |
-- - [[Backends]] are the targets for optimized code output specific to a
--   platform
-- - Currently the LLVM backend will serve as the reference
--   implementation
-- - The following backends are planned
--   1. LLVM
--   2. Michelson
--   3. WASM
--      - Most likely through LLVM
--   4. Various Arithmetic Circuits
--      - For use in ZKP's
module Juvix.Backends where
