name:                translate
version:             0.1.0.0
github:              "githubuser/Translate"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/Translate#readme>

dependencies:
- base >= 4.11 && < 5
- standard-library
- core
- frontend
- extensible-data
- unordered-containers
- lens
- containers
- dlist
- syb

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - DerivingVia
  - MultiWayIf
  - DataKinds
  - TypeApplications
  - ConstraintKinds
  - PatternSynonyms
  - FlexibleContexts
  - FlexibleInstances
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
  - NamedFieldPuns
  - DisambiguateRecordFields
  - TupleSections
  - DeriveGeneric
  - DeriveDataTypeable
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - BlockArguments

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -fno-warn-missing-pattern-synonym-signatures
  - -j
  - -static
  - -fwrite-ide-info

library:
  source-dirs: src

tests:
  translate-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - translate
    - tasty
    - tasty-hunit
    - tasty-silver
    - tasty-quickcheck
    - text
    - bytestring
    - attoparsec
